# Generated by ChatGPT on 2026-02-24
from django.db import migrations, models
import django.db.models.deletion


def forwards_fill_addon_category(apps, schema_editor):
    """Garante que todos os AddOn existentes tenham uma categoria antes de tornar o campo obrigatório."""
    AddOnCategory = apps.get_model("catalog", "AddOnCategory")
    AddOn = apps.get_model("catalog", "AddOn")

    default_cat, _ = AddOnCategory.objects.get_or_create(
        name="Geral",
        defaults={"sort_order": 0},
    )

    # Preenche apenas os registros já existentes que ficaram sem categoria.
    AddOn.objects.filter(category__isnull=True).update(category=default_cat)



class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_addon"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOnCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Categoria de opcionais",
                "verbose_name_plural": "Categorias de opcionais",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="addon",
            name="category",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addons",
                to="catalog.addoncategory",
            ),
        ),

        # Migração de dados: cria uma categoria padrão e aplica nos opcionais antigos
        migrations.RunPython(forwards_fill_addon_category, migrations.RunPython.noop),
        migrations.AddField(
            model_name="addon",
            name="is_free",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, este opcional será tratado como gratuito (R$ 0,00) mesmo que o preço esteja preenchido.",
                verbose_name="Gratuito",
            ),
        ),
        migrations.RemoveField(
            model_name="addon",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="addons",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.addon",
                verbose_name="Opcionais disponíveis",
            ),
        ),
        migrations.CreateModel(
            name="ProductAddOnRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True, verbose_name="Ativo")),
                ("min_select", models.PositiveIntegerField(default=0, verbose_name="Mínimo (obrigatório)")),
                ("max_select", models.PositiveIntegerField(default=0, verbose_name="Máximo (0 = sem limite)")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_rules",
                        to="catalog.addoncategory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon_rules",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de opcionais",
                "verbose_name_plural": "Regras de opcionais",
                "ordering": ["category__sort_order", "category__name"],
                "unique_together": {("product", "category")},
            },
        ),
        # Tornar category obrigatório depois que o banco estiver zerado:
        migrations.AlterField(
            model_name="addon",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addons",
                to="catalog.addoncategory",
            ),
        ),
    ]
