# Generated by Django 6.0.2 on 2026-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ifood_addons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['category__sort_order', 'category__name', 'name'], 'verbose_name': 'Opcional', 'verbose_name_plural': 'Opcionais'},
        ),
        migrations.AlterField(
            model_name='addoncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productaddonrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
