# Generated by Django 6.0.2 on 2026-02-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_addon_options_alter_addoncategory_id_and_more'),
        ('catalog', '0006_product_promo_imagefield'),
    ]

    operations = [
    ]
