# Generated by ChatGPT on 2026-02-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="max_flavors",
            field=models.PositiveSmallIntegerField(
                default=1,
                verbose_name="Máx. de sabores",
                help_text="Quantos sabores diferentes podem ser escolhidos neste tamanho (ex.: 2 para meio-a-meio).",
            ),
        ),
    ]
