# Generated by ChatGPT on 2026-02-28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_set_default_max_flavors_grande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.CharField(
                choices=[("P", "Pequena"), ("M", "Média"), ("G", "Grande"), ("BIG", "Big")],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="allow_mix_categories",
            field=models.BooleanField(
                default=False,
                verbose_name="Permitir misturar doce/salgada",
                help_text=(
                    "Se desmarcado, só permite escolher sabores da mesma categoria do sabor base. "
                    "Se marcado, permite misturar categorias (ex.: doce + salgada)."
                ),
            ),
        ),
    ]
