# Generated by ChatGPT on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_productsize_allow_mix_and_size_len"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[("PIZZA", "Pizza (Sabores)"), ("DRINK", "Bebidas")],
                default="PIZZA",
                max_length=10,
            ),
        ),
    ]
