# Generated by ChatGPT on 2026-01-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("ENTREGA", "Entrega"), ("RETIRADA", "Retirada no balcão")],
                default="ENTREGA",
                max_length=20,
            ),
        ),
    ]
