# Generated by ChatGPT on 2026-02-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_user_and_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_point',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
