# Generated by Django 6.0.2 on 2026-02-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_sitesettings_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_customer_message',
            field=models.TextField(default='Olá {nome}! Aqui é da pizzaria 🙂\nRecebemos seu pedido #{pedido}.\nTotal: R$ {total}\nEntrega/Retirada: {tipo_entrega}\n\nItens:\n{itens}\n\nQualquer dúvida, responda por aqui.', help_text='Mensagem para enviar ao cliente. Variáveis: {nome}, {pedido}, {total}, {tipo_entrega}, {itens}, {pagamento}, {endereco}, {referencia}'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_out_for_delivery_message',
            field=models.TextField(default='Olá {nome}! 🙂\nSeu pedido #{pedido} saiu para entrega! 🛵🍕\nTotal: R$ {total}\nPagamento: {pagamento}\n\nQualquer dúvida, pode responder por aqui.', help_text="Mensagem enviada ao cliente quando o status mudar para 'SAIU' (saiu para entrega). Variáveis: {nome}, {telefone}, {pedido}, {total}, {tipo_entrega}, {itens}, {pagamento}, {endereco}, {referencia}"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_store_message',
            field=models.TextField(default='🍕 *NOVO PEDIDO* #{pedido}\nCliente: {nome}\nWhatsApp: {telefone}\nEntrega/Retirada: {tipo_entrega}\nPagamento: {pagamento}\nEndereço: {endereco}\n\nItens:\n{itens}\n\nTotal: R$ {total}', help_text='Mensagem para enviar para a pizzaria. Variáveis: {nome}, {telefone}, {pedido}, {total}, {tipo_entrega}, {itens}, {pagamento}, {endereco}, {referencia}'),
        ),
    ]
