# Generated by Django 6.0.2 on 2026-02-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_sitesettings_whatsapp_customer_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Opcional do item',
                'verbose_name_plural': 'Opcionais dos itens',
                'ordering': ['id'],
            },
        ),
    ]
