# Generated by ChatGPT on 2026-02-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_orderitemaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemaddon",
            name="qty",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
