# Generated by Django 6.0.2 on 2026-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_sitesettings_store_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='store_closed_message',
            field=models.CharField(blank=True, default='Estamos fechados no momento. Volte mais tarde 🙂', max_length=160, verbose_name='Mensagem quando fechado'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='store_is_open',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o cardápio mostra que o estabelecimento está fechado e bloqueia novos pedidos.', verbose_name='Pizzaria aberta?'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_out_for_delivery_message',
            field=models.TextField(default='Olá {nome}! 🙂\nSeu pedido #{pedido} saiu para entrega! 🛵🍕\nTotal: R$ {total}\nPagamento: {pagamento}\n\nQualquer dúvida, pode responder por aqui.', help_text="Mensagem enviada ao cliente quando o status mudar para 'SAIU'. Variáveis: {nome}, {telefone}, {pedido}, {total}, {tipo_entrega}, {itens}, {pagamento}, {endereco}, {referencia}"),
        ),
    ]
