# Generated by ChatGPT on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_alter_sitesettings_store_closed_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_cpf",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
    ]
